version: '2'
services:
  chrome:
    build: .
    environment:
      PORT: 3000
      TIMEOUT: 30000
  nginx:
    build: 
      dockerfile: ./Dockerfile-nginx
      context: .
    ports:
      - 8000:8000
