version: '2'
services:
  chrome:
    build: .
    environment:
      PORT: 3005
      TIMEOUT: 30000
  nginx:
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
